let availables = [
  {
    name: "The Batman",
    date: "Jueves 17/3",
    hour: "19:30",
    hall: "2",
    tickets: "48",
  },
  {
    name: "The Batman",
    date: "Sábado 19/3",
    hour: "21",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Scream",
    date: "Miércoles 16/3",
    hour: "22",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Scream",
    date: "Viernes 18/3",
    hour: "21",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Kimi",
    date: "Martes 15/3",
    hour: "22",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Kimi",
    date: "Domingo 20/3",
    hour: "19:30",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Nightmare Alley",
    date: "Jueves 17/3",
    hour: "22",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Nightmare Alley",
    date: "Miércoles 23/3",
    hour: "19:30",
    hall: "2",
    tickets: "48",
  },
  {
    name: "My Hero Academia: World Heroes' Mission",
    date: "Martes 15/3",
    hour: "19:30",
    hall: "2",
    tickets: "48",
  },
  {
    name: "My Hero Academia: World Heroes' Mission",
    date: "Lunes 21/3",
    hour: "21",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Pursuit",
    date: "Martes 15/3",
    hour: "21",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Pursuit",
    date: "Domingo 20/3",
    hour: "22",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Hotel Transylvania: Transformania",
    date: "Martes 15/3",
    hour: "18:30",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Hotel Transylvania: Transformania",
    date: "Domingo 20/3",
    hour: "18:30",
    hall: "1",
    tickets: "48",
  },
  {
    name: "The Requin",
    date: "Sábado 19/3",
    hour: "22",
    hall: "2",
    tickets: "48",
  },
  {
    name: "The Requin",
    date: "Miércoles 23/3",
    hour: "21",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Sing 2",
    date: "Miércoles 16/3",
    hour: "18:30",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Sing 2",
    date: "Sábado 19/3",
    hour: "18:30",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Uncharted",
    date: "Martes 16/3",
    hour: "19:30",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Uncharted",
    date: "Jueves 24/3",
    hour: "22",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Marry Me",
    date: "Viernes 18/3",
    hour: "18:30",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Marry Me",
    date: "Lunes 21/3",
    hour: "19:30",
    hall: "2",
    tickets: "48",
  },
  {
    name: "The Hunting",
    date: "Miércoles 16/3",
    hour: "21",
    hall: "1",
    tickets: "48",
  },
  {
    name: "The Hunting",
    date: "Lunes 21/3",
    hour: "22",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Resident Evil: Welcome to Raccoon City",
    date: "Jueves 17/3",
    hour: "21",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Resident Evil: Welcome to Raccoon City",
    date: "Domingo 20/3",
    hour: "21",
    hall: "1",
    tickets: "48",
  },
  {
    name: "The 355",
    date: "Viernes 18/3",
    hour: "19:30",
    hall: "2",
    tickets: "48",
  },
  {
    name: "The 355",
    date: "Martes 22/3",
    hour: "18:30",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Clifford the Big Red Dog",
    date: "Jueves 17/3",
    hour: "18:30",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Clifford the Big Red Dog",
    date: "Miércoles 23/3",
    hour: "18:30",
    hall: "1",
    tickets: "48",
  },
  {
    name: "One Shot",
    date: "Sábado 19/3",
    hour: "19:30",
    hall: "2",
    tickets: "48",
  },
  {
    name: "One Shot",
    date: "Martes 22/3",
    hour: "21",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Moonfall",
    date: "Martes 22/3",
    hour: "19:30",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Moonfall",
    date: "Jueves 24/3",
    hour: "21",
    hall: "1",
    tickets: "48",
  },
  {
    name: "Wrath of Man",
    date: "Miércoles 23/3",
    hour: "22",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Wrath of Man",
    date: "Jueves 24/3",
    hour: "19:30",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Halloween Kills",
    date: "Viernes 18/3",
    hour: "22",
    hall: "2",
    tickets: "48",
  },
  {
    name: "Halloween Kills",
    date: "Martes 22/3",
    hour: "22",
    hall: "2",
    tickets: "48",
  },
  {
    name: "The Sky Is Everywhere",
    date: "Lunes 21/3",
    hour: "18:30",
    hall: "1",
    tickets: "48",
  },
  {
    name: "The Sky Is Everywhere",
    date: "Jueves 24/3",
    hour: "18:30",
    hall: "1",
    tickets: "48",
  },
];

module.exports = { availables };
