let groceries = [
  {
    id: 1,
    name: "Hot-dog Combo",
    img: "https://static.freddysusa.com/wp-content/uploads/2016/03/FRE0582-Combo-Lockup_2_V2.png",
    price: 450,
    stock: 100,
    description: "1 Hot-dog + 1 large soda",
    type: "combo",
  },
  {
    id: 2,
    name: "Nachos Combo",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0GVGHYxjgiuQWQB5aomcKATt865_Hj5DoVA&usqp=CAU",
    price: 590,
    stock: 100,
    description: "Nachos with cheese + 1 large soda",
    type: "combo",
  },
  {
    id: 3,
    name: "Mega Combo - for 2",
    img: "IMGNOT",
    price: 1100,
    stock: 100,
    description: "1 popcorn bucket + 2 large sodas + 1 candy",
    type: "combo",
  },
  {
    id: 4,
    name: "Mega Combo - for 1",
    img: "https://i.imgur.com/paxGUcb.png",
    price: 760,
    stock: 100,
    description: "1 popcorn bucket + 1 large soda",
    type: "combo",
  },
  {
    id: 5,
    name: "Family Combo",
    img: "https://pbs.twimg.com/media/Dq8yMgrXgAAdALk?format=jpg&name=medium",
    price: 1450,
    stock: 100,
    description: "3 popcorn small buckets + 4 sodas + 2 candies",
    type: "combo",
  },
  {
    id: 6,
    name: "Premium Combo",
    img: "https://pbs.twimg.com/media/DeC0ZYwU8AABc7a?format=jpg&name=large",
    price: 2200,
    stock: 100,
    description: "1 limited edition popcorn 'Batman' bucket + 1 large soda",
    type: "combo",
  },
  {
    id: 7,
    name: "Medium bag",
    img: "https://images-na.ssl-images-amazon.com/images/I/91HX9klF2zL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    price: 350,
    stock: 100,
    description: "Medium bag full of popcorn",
    type: "popcorn",
  },
  {
    id: 8,
    name: "Bucket",
    img: "https://st4.depositphotos.com/1006753/22078/i/1600/depositphotos_220783540-stock-photo-full-popcorn-bucket.jpg",
    price: 500,
    stock: 100,
    description: "Large bucket full of popcorn",
    type: "popcorn",
  },
  {
    id: 9,
    name: "Large soda",
    img: "https://www.abajournal.com/images/main_images/soda_cola_straw600px.png",
    price: 400,
    stock: 100,
    description:
      "Large soda of your choice (Seven UP, Mirinda, Common Pepsi, Zero Pepsi)",
    type: "drinks",
  },
  {
    id: 10,
    name: "Flavored water",
    img: "https://craftwater.co/wp-content/uploads/2020/03/waterfix-flavored-water.jpg",
    price: 260,
    stock: 100,
    description: "Flavored water of your choice",
    type: "drinks",
  },
  {
    id: 11,
    name: "Water",
    img: "https://www.nestlepurezavital.com.ar/sites/g/files/xknfdk566/files/product-16-9-oz.png",
    price: 230,
    stock: 100,
    description: "Bottle of water",
    type: "drinks",
  },
  {
    id: 12,
    name: "Nachos with cheese",
    img: "https://www.mashed.com/img/gallery/mistakes-everyone-makes-when-making-nacho-cheese/intro-1544049574.jpg",
    price: 460,
    stock: 100,
    description: "Nachos with hot cheddar",
    type: "snacks",
  },
  {
    id: 13,
    name: "Hot-dog",
    img: "https://www.wikihow.com/images/thumb/0/09/Boil-a-Hot-Dog-Step-13-Version-3.jpg/v4-728px-Boil-a-Hot-Dog-Step-13-Version-3.jpg.webp",
    price: 300,
    stock: 100,
    description: "1 Hot-dog with 2 toppings of your choice",
    type: "snacks",
  },
  {
    id: 14,
    name: "Large coffe + cookie",
    img: "https://www.publicdomainpictures.net/pictures/240000/nahled/coffee-with-cookies.jpg",
    price: 620,
    stock: 100,
    description: " 1 large coffe and 1 cookie of your choice",
    type: "coffeshop",
  },
  {
    id: 15,
    name: "Large coffe",
    img: "https://media.tegna-media.com/assets/WPMT/images/b23fd704-2a88-453c-b7fd-082c33c901cc/b23fd704-2a88-453c-b7fd-082c33c901cc_1140x641.jpeg",
    price: 450,
    stock: 100,
    description: "1 large coffe",
    type: "coffeshop",
  },
  {
    id: 16,
    name: "Medium coffe + cookie",
    img: "",
    price: 450,
    stock: 100,
    description: " 1 medium coffe and 1 cookie of your choice",
    type: "coffeshop",
  },
  {
    id: 17,
    name: "Medium coffe",
    img: "https://s3.envato.com/files/191431313/04_Paper-Coffee-Cup-Medium-Mock-Up.jpg",
    price: 280,
    stock: 100,
    description: " 1 medium coffe",
    type: "coffeshop",
  },
  {
    id: 18,
    name: "Large Rocklets",
    img: "https://7483c243aa9da28f329c-903e05bc00667eb97d832a11f670edad.ssl.cf1.rackcdn.com/20253852_1-qDmHWtQT-large.jpg",
    price: 640,
    stock: 100,
    description: " 1 Rocklets",
    type: "sweets",
  },
  {
    id: 19,
    name: "Small chocolate",
    img: "https://sweetalk.co.za/wp-content/uploads/2020/04/thanks-for-your-supportl_small-chocolate-bar_sweetalk.jpg",
    price: 330,
    stock: 100,
    description: "1 small chocolate of your choice",
    type: "sweets",
  },
  {
    id: 20,
    name: "Gummies",
    img: "https://images-na.ssl-images-amazon.com/images/I/51YW0tX7xBL._SX300_SY300_QL70_FMwebp_.jpg",
    price: 350,
    stock: 100,
    description: " 1 gab of gummies",
    type: "sweets",
  },
  {
    id: 21,
    name: "Sugus",
    img: "https://www.camoga.ar/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/5/0/50010004_caramelos_masticables_sugus_x700_grs_1.jpg",
    price: 190,
    stock: 100,
    description: " 1 box of candies Sugus",
    type: "sweets",
  },
  {
    id: 22,
    name: "Chewing Gum",
    img: "https://target.scene7.com/is/image/Target/GUEST_d54a04a3-7c5d-4ac5-bae0-8f2d42a70e82?wid=800&hei=800&qlt=80&fmt=pjpeg",
    price: 80,
    stock: 100,
    description: " 1 gum of your choice",
    type: "sweets",
  },
];

module.exports = { groceries };
