let groceries = [
  {
    id: 1,
    name: "Premium Combo",
    img: "https://i.imgur.com/9pIXGBm.png",
    price: 999,
    stock: 50,
    description: "1 limited edition popcorn bucket + 1 large soda",
    typeGrocerie: "combo",
    inCart: false,
  },
  {
    id: 2,
    name: "Hot-dog Combo",
    img: "https://i.imgur.com/nZt8nBJ.png",
    price: 450,
    stock: 50,
    description: "1 Hot-dog + 1 large soda",
    typeGrocerie: "combo",
    inCart: false,
  },
  {
    id: 3,
    name: "Nachos Combo",
    img: "https://i.imgur.com/9KxSrFJ.png",
    price: 590,
    stock: 50,
    description: "Nachos with cheese + 1 large soda",
    typeGrocerie: "combo",
    inCart: false,
  },
  {
    id: 4,
    name: "Mega Combo - for 2",
    img: "https://i.imgur.com/L3G69Tc.png",
    price: 1100,
    stock: 50,
    description: "1 popcorn bucket + 2 large sodas + 1 candy",
    typeGrocerie: "offer",
    inCart: false,
  },
  {
    id: 5,
    name: "Mega Combo - for 1",
    img: "https://i.imgur.com/paxGUcb.png",
    price: 760,
    stock: 50,
    description: "1 popcorn bucket + 1 large soda",
    typeGrocerie: "combo",
    inCart: false,
  },
  {
    id: 6,
    name: "Family Combo",
    img: "https://i.imgur.com/qvixHPJ.png",
    price: 1450,
    stock: 50,
    description: "3 popcorn medium bags + 4 sodas + 2 candies",
    typeGrocerie: "combo",
    inCart: false,
  },

  {
    id: 7,
    name: "Medium bag",
    img: "https://i.imgur.com/gLecevJ.png",
    price: 350,
    stock: 50,
    description: "Medium bag full of popcorn",
    typeGrocerie: "popcorn",
    inCart: false,
  },
  {
    id: 8,
    name: "Bucket",
    img: "https://i.imgur.com/ooiuDe1.png",
    price: 500,
    stock: 50,
    description: "Large bucket full of popcorn",
    typeGrocerie: "popcorn",
    inCart: false,
  },
  {
    id: 9,
    name: "Large soda",
    img: "https://i.imgur.com/JpxIYSI.png",
    price: 400,
    stock: 50,
    description: "Large soda of your choice",
    typeGrocerie: "drinks",
    inCart: false,
  },
  {
    id: 10,
    name: "Flavored water",
    img: "https://i.imgur.com/w8oLe8E.png",
    price: 260,
    stock: 50,
    description: "Flavored water of your choice",
    typeGrocerie: "drinks",
    inCart: false,
  },
  {
    id: 11,
    name: "Water",
    img: "https://i.imgur.com/PiptQii.png",
    price: 230,
    stock: 50,
    description: "Bottle of water",
    typeGrocerie: "drinks",
    inCart: false,
  },
  {
    id: 12,
    name: "Nachos with cheese",
    img: "https://i.imgur.com/jCNqJBt.png",
    price: 460,
    stock: 50,
    description: "Nachos with hot cheddar",
    typeGrocerie: "snacks",
    inCart: false,
  },
  {
    id: 13,
    name: "Hot-dog",
    img: "https://i.imgur.com/OdV5vpT.png",
    price: 300,
    stock: 50,
    description: "1 Hot-dog with 2 toppings of your choice",
    typeGrocerie: "snacks",
    inCart: false,
  },
  {
    id: 14,
    name: "Large coffe + cookie",
    img: "https://i.imgur.com/l0mhxkB.png",
    price: 620,
    stock: 50,
    description: " 1 large coffe and 1 cookie of your choice",
    typeGrocerie: "coffeshop",
    inCart: false,
  },
  {
    id: 15,
    name: "Large coffe",
    img: "https://i.imgur.com/HB2J2v1.png",
    price: 450,
    stock: 50,
    description: "1 large coffe",
    typeGrocerie: "coffeshop",
    inCart: false,
  },
  {
    id: 16,
    name: "Coffe + cookie",
    img: "https://i.imgur.com/H9MLjvy.png",
    price: 450,
    stock: 50,
    description: " 1 medium coffe and 1 cookie of your choice",
    typeGrocerie: "coffeshop",
    inCart: false,
  },
  {
    id: 17,
    name: "Medium coffe",
    img: "https://i.imgur.com/wQoRhs4.png",
    price: 280,
    stock: 50,
    description: " 1 medium coffe",
    typeGrocerie: "coffeshop",
    inCart: false,
  },
  {
    id: 18,
    name: "Large Rocklets",
    img: "https://i.imgur.com/eRxLxry.png",
    price: 640,
    stock: 50,
    description: " 1 Rocklets",
    typeGrocerie: "sweets",
    inCart: false,
  },
  {
    id: 19,
    name: "Small chocolate",
    img: "https://i.imgur.com/essclJj.png",
    price: 330,
    stock: 50,
    description: "1 small chocolate of your choice",
    typeGrocerie: "sweets",
    inCart: false,
  },
  {
    id: 20,
    name: "Gummies",
    img: "https://i.imgur.com/CMvuqmA.png",
    price: 350,
    stock: 50,
    description: " 1 gab of gummies",
    typeGrocerie: "sweets",
    inCart: false,
  },
  {
    id: 21,
    name: "Sugus",
    img: "https://i.imgur.com/tGjnTbq.png",
    price: 190,
    stock: 50,
    description: " 1 box of candied sugus",
    typeGrocerie: "sweets",
    inCart: false,
  },
  {
    id: 22,
    name: "Chewing Gum",
    img: "https://i.imgur.com/FbkzN0j.png",
    price: 80,
    stock: 50,
    description: " 1 gum of your choice",
    typeGrocerie: "sweets",
    inCart: false,
  },
];


module.exports = { groceries };
