const moviesdb = [
  {
    title: "Turning Red",
    img: "https://image.tmdb.org/t/p/w500/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
    description:
      "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
    popularity: 7663.359,
    release_date: "2022-03-10",
    languages: "en",
    vote_average: 7.4,
    trailer: "https://youtu.be/5IdjR-8MNSE",
    price: "1000",
    movie_genre: ["Animation", "Family", "Comedy", "Fantasy"],
  },
  {
    title: "Kimi",
    img: "https://image.tmdb.org/t/p/w500/okNgwtxIWzGsNlR3GsOS0i0Qgbn.jpg",
    description:
      "A tech worker with agoraphobia discovers recorded evidence of a violent crime but is met with resistance when she tries to report it. Seeking justice, she must do the thing she fears the most: she must leave her apartment.",
    popularity: 1102.911,
    release_date: "2022-02-10",
    languages: "en",
    vote_average: 6.3,
    trailer: "https://youtu.be/t5Pm2NBeoKM",
    price: "1000",
    movie_genre: ["Thriller"],
  },
  {
    title: "Sing 2",
    img: "https://image.tmdb.org/t/p/w500/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
    description:
      "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
    popularity: 1034.021,
    release_date: "2021-03-01",
    languages: "en",
    vote_average: 8.2,
    trailer: "https://youtu.be/_7YRovTBEEU",
    price: "1000",
    movie_genre: ["Fantasy", "Comedy", "Family", "Music"],
  },
  {
    title: "Marry Me",
    img: "https://image.tmdb.org/t/p/w500/ko1JVbGj4bT8IhCWqjBQ6ZtF2t.jpg",
    description:
      "Music superstars Kat Valdez and Bastian are getting married before a global audience of fans. But when Kat learns, seconds before her vows, that Bastian has been unfaithful, she decides to marry Charlie, a stranger in the crowd, instead.",
    popularity: 621.934,
    release_date: "2022-02-09",
    languages: "en",
    vote_average: 6.8,
    trailer: "https://youtu.be/8hXboMXWavE",
    price: "1000",
    movie_genre: ["Romance", "Comedy", "Music"],
  },
  {
    title: "Blacklight",
    img: "https://image.tmdb.org/t/p/w500/bv9dy8mnwftdY2j6gG39gCfSFpV.jpg",
    description:
      "Travis Block is a shadowy Government agent who specializes in removing operatives whose covers have been exposed. He then has to uncover a deadly conspiracy within his own ranks that reaches the highest echelons of power.",
    popularity: 345.215,
    release_date: "2022-02-10",
    languages: "en",
    vote_average: 5.6,
    trailer: "https://youtu.be/uPlCr1FFTZI",
    price: "1000",
    movie_genre: ["Action", "Thriller"],
  },
  {
    title: "Hotel Transylvania: Transformania",
    img: "https://image.tmdb.org/t/p/w500/teCy1egGQa0y8ULJvlrDHQKnxBL.jpg",
    description:
      "When Van Helsing's mysterious invention, the \"Monsterfication Ray,\" goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before it's too late, and before they drive each other crazy.",
    popularity: 189.6,
    release_date: "2022-02-25",
    languages: "en",
    vote_average: 7.1,
    trailer: "https://youtu.be/xS-4wF89eT4",
    price: "1000",
    movie_genre: ["Fantasy", "Family", "Fantasy", "Comedy", "Adventure"],
  },
  {
    title: "Nightmare Alley",
    img: "https://image.tmdb.org/t/p/w500/vfn1feL0V9HNSXuLLpaxAW8O6LO.jpg",
    description:
      "An ambitious carnival man with a talent for manipulating people with a few well-chosen words hooks up with a female psychiatrist who is even more dangerous than he is.",
    popularity: 1099.529,
    release_date: "2021-Adventure-02",
    languages: "en",
    vote_average: 7.1,
    trailer: "https://youtu.be/Q81Yf46Oj3s",
    price: "1000",
    movie_genre: ["Crime", "Drama", "Thriller"],
  },
  {
    title: "The Bad Guys",
    img: "https://image.tmdb.org/t/p/w500/1s0em1CVrM1e6fsafiNePXqh6Hv.jpg",
    description:
      "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
    popularity: 658.696,
    release_date: "2022-03-17",
    languages: "en",
    vote_average: 9,
    trailer: "https://youtu.be/m8Xt0yXaDPU",
    price: "1000",
    movie_genre: ["Fantasy", "Comedy", "Action", "Family", "Crime"],
  },
  {
    title: "Wrath of Man",
    img: "https://image.tmdb.org/t/p/w500/M7SUK85sKjaStg4TKhlAVyGlz3.jpg",
    description:
      "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
    popularity: 237.56,
    release_date: "2021-04-22",
    languages: "en",
    vote_average: 7.7,
    trailer: "https://youtu.be/zVSKWjLTFUw",
    price: "1000",
    movie_genre: ["Action", "Crime", "Thriller"],
  },
  {
    title: "The Batman",
    img: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    description:
      "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    popularity: 2675.236,
    release_date: "2022-03-01",
    languages: "en",
    vote_average: 8,
    trailer: "https://youtu.be/fWQrd6cwJ0A",
    price: "1000",
    movie_genre: ["Crime", "Mystery", "Thriller"],
  },
  {
    title: "Uncharted",
    img: "https://image.tmdb.org/t/p/w500/sqLowacltbZLoCa4KYye64RvvdQ.jpg",
    description:
      "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
    popularity: 731.16,
    release_date: "2022-02-10",
    languages: "en",
    vote_average: 7.1,
    trailer: "https://youtu.be/kVgsnqAp0Kk",
    price: "1000",
    movie_genre: ["Action", "Adventure"],
  },
  {
    title: "Moonfall",
    img: "https://image.tmdb.org/t/p/w500/odVv1sqVs0KxBXiA8bhIBlPgalx.jpg",
    description:
      "A mysterious force knocks the moon from its orbit around Earth and sends it hurtling on a collision course with life as we know it.",
    popularity: 344.43,
    release_date: "2022-02-03",
    languages: "en",
    vote_average: 6,
    trailer: "https://youtu.be/5ZvH_pIq1Oc",
    price: "1000",
    movie_genre: ["Action", "Adventure", "Science Fiction"],
  },
  {
    title: "The Adam Project",
    img: "https://image.tmdb.org/t/p/w500/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg",
    description:
      "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his Adventure-year-old self on a mission to save the future.",
    popularity: 2137.891,
    release_date: "2022-03-11",
    languages: "en",
    vote_average: 7,
    trailer: "https://youtu.be/X9ebeNKkc08",
    price: "1000",
    movie_genre: ["Science Fiction", "Adventure", "Comedy"],
  },
  {
    title: "Desperate Riders",
    img: "https://image.tmdb.org/t/p/w500/7pYYGm1dWZGkbJuhcuaHD6nE6k7.jpg",
    description:
      "After Kansas Red rescues young Billy from a card-game shootout, the boy asks Red for help protecting his family from the outlaw Thorn, who’s just kidnapped Billy’s mother, Carol. As Red and Billy ride off to rescue Carol, they run into beautiful, tough-as-nails Leslie, who’s managed to escape Thorn’s men. The three race to stop Thorn’s wedding to Carol with guns a-blazing - but does she want to be rescued?",
    popularity: 1038.039,
    release_date: "2022-02-25",
    languages: "en",
    vote_average: 6,
    trailer: "https://youtu.be/5ribxheJCUo",
    price: "1000",
    movie_genre: ["Action"],
  },
  {
    title: "The Comedy",
    img: "https://image.tmdb.org/t/p/w500/zxizwEPE8jhpbMgrFbwCztgvh2m.jpg",
    description:
      "A group of top female agents from American, British, Chinese, Columbian and German  government agencies are drawn together to try and stop an organization from acquiring a deadly weapon to send the world into chaos.",
    popularity: 685.997,
    release_date: "2022-01-05",
    languages: "en",
    vote_average: 6,
    trailer: "https://youtu.be/CGo9BEyASes",
    price: "1000",
    movie_genre: ["Action", "Thriller"],
  },
  {
    title: "The Exorcism of God",
    img: "https://image.tmdb.org/t/p/w500/pcqo9D8Bdppt6t9fBliJYPROZkv.jpg",
    description:
      "An American priest working in Mexico is considered a saint by many local parishioners. However, due to a botched exorcism, he carries a secret that’s eating him alive until he gets an opportunity to face his demon one final time.",
    popularity: 261.079,
    release_date: "2022-02-10",
    languages: "en",
    vote_average: 5.6,
    trailer: "https://youtu.be/Soxe-QkMd1A",
    price: "1000",
    movie_genre: ["Horror"],
  },
  {
    title: "Scream",
    img: "https://image.tmdb.org/t/p/w500/kZNHR1upJKF3eTzdgl5V8s8a4C3.jpg",
    description:
      "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
    popularity: 1191.305,
    release_date: "2022-01-Adventure",
    languages: "en",
    vote_average: 6.8,
    trailer: "https://youtu.be/vXu42I7_yk0",
    price: "1000",
    movie_genre: ["Horror", "Mystery", "Thriller"],
  },
  {
    title: "Gold",
    img: "https://image.tmdb.org/t/p/w500/ejXBuNLvK4kZ7YcqeKqUWnCxdJq.jpg",
    description:
      "In the not-too-distant future, two drifters traveling through the desert stumble across the biggest gold nugget ever found and the dream of immense wealth and greed takes hold. They hatch a plan to excavate their bounty, with one man leaving to secure the necessary tools while the other remains with the gold. The man who remains must endure harsh desert elements, ravenous wild dogs, and mysterious intruders, while battling the sinking suspicion that he has been abandoned to his fate.",
    popularity: 1050.706,
    release_date: "2022-01-13",
    languages: "en",
    vote_average: 6.6,
    trailer: "https://youtu.be/9UHxMBhFy88",
    price: "1000",
    movie_genre: ["Thriller", "Action"],
  },
  {
    title: "Pursuit",
    img: "https://image.tmdb.org/t/p/w500/oUU6blOmIu155vfIgzML3ZSsDrB.jpg",
    description:
      "Detective Breslin crosses paths with Calloway, a ruthless hacker desperate to find his wife, who has been kidnapped by a drug cartel. When Calloway escapes police custody, Breslin joins forces with a no-nonsense female cop to reclaim his prisoner. But is Calloway’s crime-boss father somehow involved in this explosive situation?",
    popularity: 962.091,
    release_date: "2022-02-Drama",
    languages: "en",
    vote_average: 5.7,
    trailer: "https://youtu.be/7YEicjmt2KY",
    price: "1000",
    movie_genre: ["Action", "Crime", "Thriller"],
  },
  {
    title: "Clifford the Big Red Dog",
    img: "https://image.tmdb.org/t/p/w500/oifhfVhUcuDjE61V5bS5dfShQrm.jpg",
    description:
      "As Emily struggles to fit in at home and at school, she discovers a small red puppy who is destined to become her best friend. When Clifford magically undergoes one heck of a growth spurt, becomes a gigantic dog and attracts the attention of a genetics company, Emily and her Uncle Casey have to fight the forces of greed as they go on the run across New York City. Along the way, Clifford affects the lives of everyone around him and teaches Emily and her uncle the true meaning of acceptance and unconditional love.",
    popularity: 607.973,
    release_date: "2021-11-10",
    languages: "en",
    vote_average: 7.3,
    trailer: "https://youtu.be/HU3PtgrtaM4",
    price: "1000",
    movie_genre: ["Family", "Adventure", "Comedy", "Fantasy"],
  },
];

module.exports = { moviesdb };
